fix: update, reword and add to README.md.
AnimaApp/anima-storybook-cli pull request #10
Opened 2023-01-27 15:25 UTC by RyanHavoc

I've been through an update the `README.md` for the cli. We had some missing information and consistencies in wording. I think it reads better now.

I've also added some information about a bug we're aware of in Storybook and how to work around it.

This PR - https://github.com/AnimaApp/anima-design-to-code/pull/830 - makes a point of linking to this documentation which sparked the updating.

Asana task: https://app.asana.com/0/0/1203830048747724/f

2023-01-27 15:56 UTC, jorgemartins commented on README.md
> +6. **Figma:** The Anima Plugin will update to show that your Storybook is connected. Enter `Cmd + L` or `Ctrl + L` to copy your Figma project link and paste it into *Paste Figma link here* field.
I think we don't need to overstate this step on the readme.

2023-01-27 15:58 UTC, jorgemartins commented on README.md
> +  </h1>
why remove the dark mode asset :( GitHub automatically shows/hides the asset depending on the user configuration

2023-01-27 16:02 UTC, jorgemartins requested changes

2023-01-27 16:02 UTC, jorgemartins commented on README.md
> +    <img src="https://user-images.githubusercontent.com/1323193/201663351-171f5916-bf03-44e0-9d9a-f5c69d3e3ec8.svg#gh-light-mode-only" width="250" alt="Anima Command line interface" />
```suggestion
    <img src="https://user-images.githubusercontent.com/1323193/201663351-171f5916-bf03-44e0-9d9a-f5c69d3e3ec8.svg#gh-light-mode-only" width="250" alt="Anima Command line tool" />
```

2023-01-27 16:02 UTC, jorgemartins commented on README.md
> +  </h1>
```suggestion
    <img src="https://user-images.githubusercontent.com/1323193/201663360-76c32bdb-c4e4-43af-bcf7-5db760c9b71f.svg#gh-dark-mode-only" width="250" alt="Anima Command line tool" />
  </h1>
```

2023-01-27 16:02 UTC, jorgemartins commented on README.md
> +6. **Figma:** The Anima Plugin will update to show that your Storybook is connected. Enter `Cmd + L` or `Ctrl + L` to copy your Figma project link and paste it into *Paste Figma link here* field.
```suggestion

```

2023-01-27 16:02 UTC, jorgemartins commented on README.md
> +7. **Figma:** You can now import and generate your Storybook components in Figma. 🎉
```suggestion
6. **Figma:** You can now import and generate your Storybook components in Figma. 🎉
```

2023-01-27 16:03 UTC, jorgemartins commented
Overall great edits 🙏 thanks

2023-01-27 16:36 UTC, RyanHavoc commented on README.md
> +6. **Figma:** The Anima Plugin will update to show that your Storybook is connected. Enter `Cmd + L` or `Ctrl + L` to copy your Figma project link and paste it into *Paste Figma link here* field.
I actually disagree... these steps didn't make sense to me when I first read them and understanding that there's actual two parts to this flow, the **Anima Storybook CLI** and the **Anima Figma Plugin** wasn't clear at all.

We could change Step 6 and Step 7 to say "Follow the onscreen instructions in Figma to start generating components 🎉"

?

2023-01-27 16:38 UTC, RyanHavoc commented on README.md
> +  </h1>
Maybe, but Storybook doesn't.

<img width="1386" alt="Screenshot 2023-01-27 at 16 37 19" src="https://user-images.githubusercontent.com/824169/215142329-50f66ce2-1569-4fb4-ba69-47819677e259.png">

Our addon in Storybook library is showing both logos and looks broken.

2023-01-27 16:40 UTC, RyanHavoc commented on README.md
> +    <img src="https://user-images.githubusercontent.com/1323193/201663351-171f5916-bf03-44e0-9d9a-f5c69d3e3ec8.svg#gh-light-mode-only" width="250" alt="Anima Command line interface" />
Why change it to "tool" here, the logo says Anima CLI. If we were to be accurate we should change this to "Anima CLI"?

2023-01-27 16:43 UTC, RyanHavoc commented on README.md
> +6. **Figma:** The Anima Plugin will update to show that your Storybook is connected. Enter `Cmd + L` or `Ctrl + L` to copy your Figma project link and paste it into *Paste Figma link here* field.
Made a change, have a look?

2023-01-27 17:12 UTC, jorgemartins commented on README.md
> +6. **Figma:** The Anima Plugin will update to show that your Storybook is connected. Enter `Cmd + L` or `Ctrl + L` to copy your Figma project link and paste it into *Paste Figma link here* field.
that's even better 👍

2023-01-27 17:17 UTC, jorgemartins commented on README.md
> +    <img src="https://user-images.githubusercontent.com/1323193/201663351-171f5916-bf03-44e0-9d9a-f5c69d3e3ec8.svg#gh-light-mode-only" width="250" alt="Anima Command line interface" />
oh thought we should change here too after you've changed in the read me. I was auto pilot mode, but now that i look closer the alt should even be more descriptive like "Anima Command line interface logo" ?

2023-01-27 17:37 UTC, jorgemartins commented on README.md
> +  </h1>
I think Storybook's integration page doesn't even update the readme when there are changes 😓  I'm afraid that all this effort will not be reflected there.
Either way I really think we shouldn't botcher Github's presentation because of how storybook renders the readme, specially because the change will not fix it anyway.

2023-01-30 09:24 UTC, jorgemartins approved these changes

2023-01-30 09:25 UTC, merged