feature: sync design tokens only
AnimaApp/anima-storybook-cli pull request #34
Opened 2023-05-02 09:31 UTC by andrico-anima

https://www.loom.com/share/0fd7aee4ddaa40b08468c18e567d75fa

https://app.asana.com/0/1204315207094721/1204485586761684/f

2023-05-02 18:15 UTC, Datlyfe requested changes
Great job, couple comments

2023-05-02 18:15 UTC, Datlyfe commented on src/helpers/file-system.ts
> +export const getFileIfExists = async <T>(path?: string): Promise<T | undefined> => {
```suggestion
export const getFileOrThrow= async <T>(path?: string): Promise<T | undefined> => {
```

2023-05-02 18:15 UTC, Datlyfe commented on src/api/storybook.ts
> +    op: 'get-or-create-storybook',
```suggestion
    op: 'get-or-create-storybook-for-design-tokens',
```

2023-05-02 18:15 UTC, Datlyfe commented on src/commands/sync-design-tokens.ts
> +  const response = await authenticate(token);
There is a small issue here, authenticating with the token will set `is_storybook_paired` to `true` on the api, which is a side effect that we need to remove and do it explicity not everytime the token is being verified, something to keep in mind but lets create a ticket about this please.

2023-05-02 18:15 UTC, Datlyfe commented on src/commands/sync-design-tokens.ts
> +    op: 'upload-process',
```suggestion
    op: 'update-design-tokens',
```

2023-05-03 08:04 UTC, andrico-anima commented on src/helpers/file-system.ts
> +export const getFileIfExists = async <T>(path?: string): Promise<T | undefined> => {
done!

2023-05-03 08:05 UTC, andrico-anima commented on src/api/storybook.ts
> +    op: 'get-or-create-storybook',
done!

2023-05-03 08:05 UTC, andrico-anima commented on src/commands/sync-design-tokens.ts
> +  const response = await authenticate(token);
Will do!

2023-05-03 08:08 UTC, andrico-anima commented on src/commands/sync-design-tokens.ts
> +  const response = await authenticate(token);
https://app.asana.com/0/1203335192450540/1204521282059336/f

2023-05-03 08:09 UTC, andrico-anima commented on src/commands/sync-design-tokens.ts
> +    op: 'upload-process',
done!

2023-05-03 08:09 UTC, andrico-anima commented
Thanks for reviewing @Datlyfe

2023-05-03 08:44 UTC, Datlyfe approved these changes

2023-05-03 09:10 UTC, merged